### ISSUE TITLE
报错Error in mounted hook: "TypeError: Class constructor Vector3 cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by FangMeiyan** [fox19920726/threebsp#2]

**Comment by fox19920726** [comment]
贴一下代码，老哥

**Comment by zxxliang** [comment]
我用的最新版的three--0.120.1,
tthreebsp版本-1.0.8；
在执行官方文档中 new ThreeBSP(sphere)时就报这个错误
TypeError: Class constructor Vector3 cannot be invoked without 'new'

**Comment by fox19920726** [comment]
tthreebsp 版本升一下，用1.0.9试试

**Comment by Evenssi** [comment]
嗯遇到了一样的问题。求救呀

**Comment by fox19920726** [comment]
> 嗯遇到了一样的问题。求救呀

1.0.9也不行吗

**Comment by Evenssi** [comment]
嗯嗯,我换了threejs的版本了，好像不行，后来找了一个three-js-csg的包，可以用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "23"<notifications@github.com&gt;; 
发送时间: 2020年11月23日(星期一) 晚上8:50
收件人: "fox19920726/threebsp"<threebsp@noreply.github.com&gt;; 
抄送: "Evenssi"<741005294@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [fox19920726/threebsp] 报错Error in mounted hook: &quot;TypeError: Class constructor Vector3 cannot be invoked without &#39;new&#39;&quot; (#2)





  
嗯遇到了一样的问题。求救呀
  
1.0.9也不行吗

**Comment by fox19920726** [comment]
尴尬。。。我咋能用，哈哈哈哈哈

**Comment by fox19920726** [comment]
> 嗯嗯,我换了threejs的版本了，好像不行，后来找了一个three-js-csg的包，可以用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "23"<notifications@github.com&gt;; 发送时间: 2020年11月23日(星期一) 晚上8:50 收件人: "fox19920726/threebsp"<threebsp@noreply.github.com&gt;; 抄送: "Evenssi"<741005294@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [fox19920726/threebsp] 报错Error in mounted hook: &quot;TypeError: Class constructor Vector3 cannot be invoked without &#39;new&#39;&quot; (#2) 嗯遇到了一样的问题。求救呀 1.0.9也不行吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

尴尬。。。我咋能用，哈哈哈哈哈

**Comment by Evenssi** [comment]
你是换的threejs版本吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "23"<notifications@github.com&gt;; 
发送时间: 2020年11月23日(星期一) 晚上8:57
收件人: "fox19920726/threebsp"<threebsp@noreply.github.com&gt;; 
抄送: "Evenssi"<741005294@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [fox19920726/threebsp] 报错Error in mounted hook: &quot;TypeError: Class constructor Vector3 cannot be invoked without &#39;new&#39;&quot; (#2)





 
尴尬。。。我咋能用，哈哈哈哈哈

**Comment by Evenssi** [comment]
我现在用的是threejs的107版本


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fox19920726/threebsp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上8:57
收件人:&nbsp;"fox19920726/threebsp"<threebsp@noreply.github.com&gt;;
抄送:&nbsp;"Evenssi"<741005294@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fox19920726/threebsp] 报错Error in mounted hook: "TypeError: Class constructor Vector3 cannot be invoked without 'new'" (#2)





 
尴尬。。。我咋能用，哈哈哈哈哈

**Comment by fox19920726** [comment]
> 用的是threejs的107版本

    "three": "^0.110.0",
    "three-orbit-controls": "^82.1.0",
    "tthreebsp": "^1.0.9",
    "vue": "^2.6.10"

**Comment by FangMeiyan** [comment]
忘记之前提的issue了。贴一下我这边的解决方法。

 **在webpack.base.conf.js文件里面rules js那块加一下resolve('node_modules/three')**

![image](https://user-images.githubusercontent.com/48247261/123888421-0d7be300-d986-11eb-8bc1-a559d4c88b11.png)

**！！不过注意：用这种方法的话如果你项目中使用了three-orbit-controls这个库会报新的错**
‘Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'’

**建议用官方的鼠标控件**：
`import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'`

我目前使用的这个版本是没问题的
`"three": "^0.120.1",
    "tthreebsp": "^1.0.9",
    "vue": "^2.5.2",`

如果three版本比较老，用官方的鼠标控件无法引入的话，可以联系我，之前因为这个问题我有改写过一个OrbitControls.js是可以正常引入的，有需要的话我去找下。

**Comment by fox19920726** [comment]
> 忘记之前提的issue了。贴一下我这边的解决方法。
> 
> **在webpack.base.conf.js文件里面rules js那块加一下resolve('node_modules/three')**
> 
> ![image](https://user-images.githubusercontent.com/48247261/123888421-0d7be300-d986-11eb-8bc1-a559d4c88b11.png)
> 
> **！！不过注意：用这种方法的话如果你项目中使用了three-orbit-controls这个库会报新的错**
> ‘Uncaught TypeError: Cannot assign to read only property 'exports' of object '#'’
> 
> **建议用官方的鼠标控件**：
> `import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'`
> 
> 我目前使用的这个版本是没问题的
> `"three": "^0.120.1", "tthreebsp": "^1.0.9", "vue": "^2.5.2",`
> 
> 如果three版本比较老，用官方的鼠标控件无法引入的话，可以联系我，之前因为这个问题我有改写过一个OrbitControls.js是可以正常引入的，有需要的话我去找下。

牛笔！！！！！！
